[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
recurring = { path = "../programs/recurring", features = ["no-entrypoint"] }
anchor-client = "0.24.2"
anchor-spl = "0.24.2"
dotenv = "0.15.0"
tokio = { version = "1.13.0", features = ["full"] }